// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_comment from "./routes/api/comment.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_post from "./routes/api/post.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $blog_posts_id_edit from "./routes/blog/posts/[id]/edit.tsx";
import * as $blog_posts_id_index from "./routes/blog/posts/[id]/index.tsx";
import * as $blog_posts_new from "./routes/blog/posts/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $Comments from "./islands/Comments.tsx";
import * as $CopyArea from "./islands/CopyArea.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LemonDrop from "./islands/LemonDrop.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $LogoutButton from "./islands/LogoutButton.tsx";
import * as $MainPage from "./islands/MainPage.tsx";
import * as $NavigationBar from "./islands/NavigationBar.tsx";
import * as $PostForm from "./islands/PostForm.tsx";
import * as $PostList from "./islands/PostList.tsx";
import * as $Style from "./islands/Style.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/comment.ts": $api_comment,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/post.ts": $api_post,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/blog/posts/[id]/edit.tsx": $blog_posts_id_edit,
    "./routes/blog/posts/[id]/index.tsx": $blog_posts_id_index,
    "./routes/blog/posts/new.tsx": $blog_posts_new,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Comments.tsx": $Comments,
    "./islands/CopyArea.tsx": $CopyArea,
    "./islands/Counter.tsx": $Counter,
    "./islands/LemonDrop.tsx": $LemonDrop,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/LogoutButton.tsx": $LogoutButton,
    "./islands/MainPage.tsx": $MainPage,
    "./islands/NavigationBar.tsx": $NavigationBar,
    "./islands/PostForm.tsx": $PostForm,
    "./islands/PostList.tsx": $PostList,
    "./islands/Style.tsx": $Style,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
